# Generated by Django 5.1.6 on 2025-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_logproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logproduct',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
