# Generated by Django 5.1.6 on 2025-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_logproduct_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logproduct',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
